### ISSUE TITLE
possibility of adding a PNP file?

### ISSUE THREAD

**Issue by MHFDoge** [hitriy/fliipper-rgb-hardware#2]
Hi, I love the work you've done for this, but I have one small request, is there any chance you could add a PNP(Pick and place) file to the gerber files? I'm somewhat familiar with KiCad but not familiar enough to reliably add it myself without worrying about/actually screwing something up. I looked through the list of files but did not see anything that stood out as one, if it's already there and I just missed it I'm sorry. Thank you!

**Comment by hitriy** [comment]
Hey!
Unfortunatelly I don't have any experience with ordering assmbled PCBs and even creataing PNP files, so this is not planned, sorry.
